project:
  type: website
  output-dir: docs

website:
  title: "Manuel Oliveira"
  favicon: assets/robots.png
  navbar:
    background: '#fcc404'
    right: 
      - icon: github
        href: https://github.com/olivethree
      - icon: linkedin
        href: https://www.linkedin.com/in/manueljbo/ 
    left:
      - href: index.qmd
        text: Home
        
      - href: blog.qmd
        text: Blog

      - href: publications.qmd
        text: Publications
      
      - href: apps.qmd
        text: Apps
      
      - href: about.qmd
        text: About
        
  page-footer: 
    left: "Copyright 2022, Manuel Oliveira" 
  
  google-analytics: 
    tracking-id: "UA-176122484-2"
    anonymize-ip: true
  
  open-graph:
    site-name: Manuel Oliveira
  
  twitter-card: true
    
execute:
  freeze: auto

format:
  html:
    theme: 
      light: lux
      dark: [lux, theme-dark-lux.scss]
      
    css: styles.css
    toc: true

editor: visual

